theme: jekyll-theme-cayman
title: Yarkın Erdoğan Progress Journal
description: IE 582 Fall 2020- Bogazici University


##HW Links

#HW0

[Here](files/example_HW0) is my 5 hot topics in Machine Learning
